version: '3'

services:
    app:
        container_name: sp_app
        build:
            context: ./Infrastructure/app
            args:
                - timezone=${TZ}
        depends_on:
            - mysql
        volumes:
#            - ./Application:/var/www/html:rw,cached
            - ./Application:/var/www/html:rw
        env_file:
            - .env
        links:
            - mysql
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${NGINX_HOST}

    mysql:
        container_name: sp_mysql
        build:
            context: ./Infrastructure/db
            dockerfile: Dockerfile.mysql
        volumes:
            - ./.data/mysql:/var/lib/mysql:rw
        env_file:
            - .env
        ports:
            - "3307:3306"

    nginx:
        container_name: sp_nginx
        build:
            context: ./Infrastructure/nginx
            args:
                - nginx_host=${NGINX_HOST}
        ports:
            - "8008:80"
            - "4443:443"
        depends_on:
            - app
        volumes:
            - ./Application/public:/var/www/html/public:ro
            - ./Infrastructure/nginx/default.template:/etc/nginx/conf.d/default.template
            - nginx_log:/var/log/nginx
        env_file:
            - .env
        command: /bin/bash -c "envsubst '$$NGINX_HOST'
            < /etc/nginx/conf.d/default.template
            > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"

    redis:
        container_name: sp_redis
        build:
            context: ./Infrastructure/redis

    rabbitmq:
        container_name: sp_rabbitmq
        image: "rabbitmq:3-management"
        hostname: "rabbitmq"
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        env_file:
            - .env
        ports:
            - "5672:5672"
        stdin_open: true
        tty: true

#        elk:
#            build:
#                context: ./Infrastructure/elk
#            ports:
#                - "5601:5601"
#                - "9200:9200"
#                - "5044:5044"
#            environment:
#                - ELASTICSEARCH_START
#                - LOGSTASH_START
#                - KIBANA_START
#                - TZ

#        filebeat:
#            build:
#                context: ./Infrastructure/elk
#                dockerfile: Dockerfile.filebeat
#            volumes:
#                - app_log:/var/log/app
#                - nginx_log:/var/log/nginx

volumes:
    nginx_log: