parameters:

services:
    # ACCOUNT BOUNDED CONTEXT


    # BET BOUNDED CONTEXT
    InnovatikLabs\Bet\TournamentPool\Application\Command\Handler\:
        resource: '../../src/Bet/TournamentPool/Application/Command/Handler'
        tags: ['messenger.message_handler']

    InnovatikLabs\Bet\TournamentPool\Application\Query\Handler\:
        resource: '../../src/Bet/TournamentPool/Application/Query/Handler'
        tags: ['messenger.message_handler']

    # GAME BOUNDED CONTEXT
