sonata_admin:
    title: 'Soccer Pools Admin'
    title_logo: 'assets/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
