sonata_admin:
    title: 'Soccer Pools Admin'
    title_logo: 'assets/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            -   class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  admin.team                # admin code - service id
                    icon:  fa-flag                # font awesome icon
                    text:  Teams
                    color: bg-yellow                 # colors: bg-green, bg-red and bg-aqua
            -   class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  admin.tournament                # admin code - service id
                    icon:  fa-trophy                # font awesome icon
                    text:  Tournaments
                    color: bg-red                 # colors: bg-green, bg-red and bg-aqua
#                    filters:                         # filter values
#                        edited: { value: 1 }
            -   class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  admin.tournament_pool                # admin code - service id
                    icon:  fa-futbol-o                # font awesome icon
                    text:  Pools Created
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
#                        filters:                         # filter values
#                            edited: { value: 1 }
            -   class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  admin.user                # admin code - service id
                    icon:  fa-users                # font awesome icon
                    text:  Playing Users
                    color: bg-blue                 # colors: bg-green, bg-red and bg-aqua
#                        filters:                         # filter values
#                            edited: { value: 1 }
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.stats:
            contexts:   [admin]
