services:
    admin.team:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\TeamAdmin
        arguments: [~, InnovatikLabs\Game\Team\Domain\Model\Team, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: General, label: Teams }

    admin.tournament:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\TournamentAdmin
        arguments: [~, InnovatikLabs\Game\Tournament\Domain\Model\Tournament, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pools, label: Tournaments }

    admin.group:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\GroupAdmin
        arguments: [~, InnovatikLabs\Game\Group\Domain\Model\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pools, label: Tournament Groups }

    admin.tournament_phase:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\TournamentPhaseAdmin
        arguments: [~, InnovatikLabs\Game\TournamentPhase\Domain\Model\TournamentPhase, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pools, label: 'Tournament Phases' }

    admin.tournament_pool:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\TournamentPoolAdmin
        arguments: [~, InnovatikLabs\Bet\TournamentPool\Domain\Model\TournamentPool, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pools, label: 'Tournament Pools' }

    admin.user:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\UserAdmin
        arguments: [~, InnovatikLabs\Account\User\Domain\Model\User, ~]
        calls:
            -   method: setUserManager
                arguments:
                    - '@fos_user.user_manager'
        tags:
            - { name: sonata.admin, manager_type: orm, group: General, label: 'Users' }

    admin.federation:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\FederationAdmin
        arguments: [~, InnovatikLabs\Game\Federation\Domain\Model\Federation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: General, label: 'Federations' }

    admin.match:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\MatchAdmin
        arguments: [~, InnovatikLabs\Game\Match\Domain\Model\Match, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pools, label: 'Tournament Matches' }

    admin.pool_ticket:
        class: InnovatikLabs\UI\Http\BackOffice\Admin\PoolTicketAdmin
        arguments: [~, InnovatikLabs\Bet\PoolTicket\Domain\Model\PoolTicket, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pools, label: 'Pool Tickets' }
